Database
AndriiKhomik/react_e-commerce_final_project pull request #15
Opened 2021-11-21 15:57 UTC by BoikoYV

2021-11-21 16:46 UTC, BoikoYV commented
![](https://github.trello.services/images/mini-trello-icon.png) [сделать тестовую БД](https://trello.com/c/uBbHv7wQ/63-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%83%D1%8E-%D0%B1%D0%B4)

2021-11-21 21:49 UTC, svrostislav requested changes

2021-11-21 21:49 UTC, svrostislav commented on config/keys_dev.js
> +  secretOrKey: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTYxMzU0NjNlOTg5MzkxZDhjYjU0MyIsImZpcnN0TmFtZSI6Ill1bGlhIiwibGFzdE5hbWUiOiJCb2lrbyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzNzQwNTQwOSw
тут не повинно бути ніякого токену

2021-11-21 21:49 UTC, svrostislav commented on controllers/authors.js
> +    author: req.params.authorId
тут мабуть треба заюзати findById

перевіряла, чи шукає воно і приходить в результаті?

2021-11-21 21:49 UTC, svrostislav commented on controllers/products.js
> -  productFields.itemNo = rand();
цей рандом також повинен залишитися тут

тому що ми виходить забрали можливіть через апі додавати продукти

2021-11-21 21:49 UTC, svrostislav commented on models/Author.js
> +      type: String,
є формат дата у нас

2021-11-21 21:49 UTC, svrostislav commented on models/Author.js
> +    dateOfDeath: {
формат дати

2021-11-21 21:49 UTC, svrostislav commented on models/Author.js
> +    popularBooks: [{
якщо ми хочемо зробити популярні книги автора, то нам потрібно робити це рефкою до колекції книг

поки пропоную це відкласти

і немає зворотньої рефки
тобто ми не можемо отримати автора і список усіх його книг

2021-11-21 21:49 UTC, svrostislav commented on models/Product.js
> +      type: String,
якщо в нас є декілька варіантів, то це type enum

https://stackoverflow.com/questions/29299477/how-to-create-and-use-enum-in-mongoose

2021-11-21 21:49 UTC, svrostislav commented on models/Product.js
> +    duration: {
ця властивість за що відповідає?

2021-11-21 21:49 UTC, svrostislav commented on package.json
> +    "seed": "nodemon seeds/seed.js"
просто `node seed/seed.js`

2021-11-21 21:49 UTC, svrostislav commented on seeds/authors.js
> +    "_id": "619670e222fce45aa6a6dd27",
_id хіба не генерує сам mongoose?

2021-11-21 22:55 UTC, BoikoYV commented on config/keys_dev.js
> +  secretOrKey: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTYxMzU0NjNlOTg5MzkxZDhjYjU0MyIsImZpcnN0TmFtZSI6Ill1bGlhIiwibGFzdE5hbWUiOiJCb2lrbyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzNzQwNTQwOSw
а что должно быть в secretOrKey?

2021-11-21 23:38 UTC, BoikoYV commented on controllers/products.js
> -  productFields.itemNo = rand();
Вернула.

Но если мы будем добавлять/изменять данные в базе(через постман или в монгодб напрямую), а потом запустим сиды, то все что мы добавили/ изменили вручную - удалится и будет то, что в сидах.
Мы сиды используем временно, а потом в продакшн базе уже не будем их использовать?

2021-11-21 23:52 UTC, BoikoYV commented on models/Author.js
> +      type: String,
Точно! Я записывала только год. Сделаю всем одинаковый месяц рождения тогда.  Мы выводим только год, остальная информация не важна. Так нормально будет?

2021-11-21 23:58 UTC, BoikoYV commented on models/Author.js
> +    popularBooks: [{
Я писала эти популярные книги, как часть биографии автора, это не ссылки и не те книги, которые у нас в магазине, а просто его известные произведения. На макете это находится на странице 1 автора в блоке об авторе. Так странно выглядит, вообще  их убрать?

2021-11-22 00:02 UTC, BoikoYV commented on models/Product.js
> +    duration: {
длительность аудиокниги в часах

2021-11-22 00:10 UTC, BoikoYV commented on seeds/authors.js
> +    "_id": "619670e222fce45aa6a6dd27",
Генерирует. Но при каждом запуске базы id меняются. А мне нужно было в книгу в поле автор передать id автора как тип ObjectId с ref на коллекцию авторов, чтобы данные об авторе подтянулись в книгу (чтобы у конкретного автора была конкретная книга). Я не нашла другой способ, как их связать :( 

Я добавляла авторов без _id. База сама генерировала этот id, я потом его копировала в объект конкретного автора и в объект книги, которую он написал (в поле автор).

Есть какое-то решение получше?

2021-11-22 00:23 UTC, BoikoYV commented on models/Product.js
> +      type: String,
для категорий (электронная, бумажная и аудио книга) и жанров(5 вариантов) тоже применить?

2021-11-22 08:56 UTC, svrostislav commented on controllers/products.js
> -  productFields.itemNo = rand();
сіди потрібні для того, щоб
* іншим можна було підключити свою базу і не наповнювати її
* прод базу наповнити готовими даними якимись відразу
* при зміні структури БД не писати міграції ще або заново наповнювати базу, а поправити сід і перезаписати базу

на готову продакшен базу сіди не запускаються потім уже

вони економлять час в загальному всій команді

2021-11-22 08:56 UTC, svrostislav commented on models/Author.js
> +      type: String,
так

2021-11-22 08:58 UTC, svrostislav commented on models/Author.js
> +    popularBooks: [{
те, що на макеті, відноситься скоріше просто до fullDescription - блоку про автора

тому якщо хочеш, можеш їх додати у вигляді ul, li туди

2021-11-22 08:59 UTC, svrostislav commented on models/Product.js
> +      type: String,
до жанрів можна

до категорій ні, тому що категорії по факту створюються в /catalog

2021-11-22 09:02 UTC, svrostislav commented on models/Product.js
> +    duration: {
о, але краще в секундах записувати або хоча б хвилинах

2021-11-22 09:13 UTC, svrostislav commented on seeds/authors.js
> +    "_id": "619670e222fce45aa6a6dd27",
заведи поки окремо таску на це

2021-11-22 09:15 UTC, BoikoYV commented on controllers/products.js
> -  productFields.itemNo = rand();
поняла)

2021-11-22 09:17 UTC, BoikoYV commented on seeds/authors.js
> +    "_id": "619670e222fce45aa6a6dd27",
суть таски разобраться с ссылкой на автора в книге?

2021-11-22 17:42 UTC, BoikoYV commented on models/Product.js
> +    duration: {
добавила в минутах. На фронте можно выводить в часах и минутах, чтобы красиво было) Например 1 час 30 минут

2021-11-22 18:05 UTC, BoikoYV commented on controllers/authors.js
> +    author: req.params.authorId
Проверила, не работало, сейчас сделала по другому, работает. findById не срабатывает наверное из-за того, что это уже не id, а ObjectId.
Работает так:  Author.findOne({
    _id: new ObjectId(req.params.id)
 })

2021-11-22 21:19 UTC, svrostislav approved these changes

2021-11-22 21:30 UTC, merged